# Generated by Django 2.2 on 2020-09-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindful_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images/'),
        ),
    ]
